services:
    rmcgirr83.topicicononindex.listener:
        class: rmcgirr83\topicicononindex\event\listener
        arguments:
            - '@auth'
            - '@cache'
            - '@dbal.conn'
            - '@language'
        tags:
            - { name: event.listener }
